# Generated by Django 4.2.20 on 2025-04-20 20:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import encrypted_field.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='account_name',
            field=encrypted_field.fields.EncryptedField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='account_number',
            field=encrypted_field.fields.EncryptedField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='Account number must be 8 digits', regex='^[0-9]{8}$')]),
        ),
        migrations.AlterField(
            model_name='claim',
            name='sort_code',
            field=encrypted_field.fields.EncryptedField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='Sort code must be 6 digits (without hyphens)', regex='^[0-9]{6}$')]),
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='A name to identify this bank account', max_length=100)),
                ('account_name', encrypted_field.fields.EncryptedField(max_length=100)),
                ('account_number', encrypted_field.fields.EncryptedField(max_length=8, validators=[django.core.validators.RegexValidator(message='Account number must be 8 digits', regex='^[0-9]{8}$')])),
                ('sort_code', encrypted_field.fields.EncryptedField(max_length=6, validators=[django.core.validators.RegexValidator(message='Sort code must be 6 digits (without hyphens)', regex='^[0-9]{6}$')])),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bank Details',
                'unique_together': {('user', 'nickname')},
            },
        ),
        migrations.AddField(
            model_name='claim',
            name='saved_bank_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='claims.bankdetails'),
        ),
    ]
